
# CMD [ "demo.lambda_handler" ]
FROM public.ecr.aws/lambda/python:3.10

# Install the function's dependencies using file requirements.txt
# from your project folder.

COPY requirements.txt  .
RUN pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

RUN pip3 install torch==2.0.1+cpu torchvision==0.15.2+cpu -f https://download.pytorch.org/whl/torch_stable.html

# Copy function code
COPY demo.py ${LAMBDA_TASK_ROOT}
COPY inference.py ${LAMBDA_TASK_ROOT}
COPY inference_dataset.py ${LAMBDA_TASK_ROOT}
COPY classifier.py ${LAMBDA_TASK_ROOT}
COPY duplicate_detection.py ${LAMBDA_TASK_ROOT}
# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "demo.lambda_handler" ]